name: Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: Run tests for adapters

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9.16"

    - name: Setup poetry
      uses: abatilo/actions-poetry@v4
      with:
        poetry-version: "1.8.4"

    - name: Install ubuntu packages
      uses: ConorMacBride/install-package@v1
      with:
        apt: 'curl'

    - name: Install dependencies and needed compilers
      run: |
        poetry install

    - name: Run tests
      run: |
        poetry run pytest tests/adapters/clickhouse -v
